# Generated by Django 4.1.3 on 2022-11-16 10:35

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="picture",
            options={
                "ordering": ("-date",),
                "verbose_name": "Picture",
                "verbose_name_plural": "Pictures",
            },
        ),
        migrations.AddField(
            model_name="picture",
            name="photo_ppoi",
            field=versatileimagefield.fields.PPOIField(
                default="0.5x0.5", editable=False, max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="picture",
            name="photo",
            field=versatileimagefield.fields.VersatileImageField(
                upload_to="uploads/", verbose_name="Photo"
            ),
        ),
    ]
